import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#07100B',
  panel: '#17281E',
  line: '#42503A',
  cream: '#F2EFDF',
  muted: '#A6B3A5',
  accent: '#F1C40F',
  green: '#78C69C',
  red: '#A92732'
};
export const s = StyleSheet.create({
  historyModalWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16 },
  historyModal: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '90%',
    padding: 16,
    borderRadius: 24,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.line
  },
  historyWin: { backgroundColor: '#153A29', borderColor: '#4BBD7D', borderLeftWidth: 4 },
  historyLoss: { backgroundColor: '#3D1C24', borderColor: '#E36973', borderLeftWidth: 4 },
  historyDraw: { backgroundColor: '#252C29', borderColor: '#87948D', borderLeftWidth: 4 },
  resultDialog: {
    width: '100%',
    maxWidth: 440,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bg,
    alignItems: 'stretch'
  },
  resultDialogLost: { borderColor: '#D74747' },
  resultEmoji: { fontSize: 54, textAlign: 'center', marginTop: 8, marginBottom: 8 },
  resultHeading: { fontSize: 25, fontWeight: '900', color: colors.accent, textAlign: 'center' },
  resultHeadingLost: { color: '#FF8585' },
  resultDescription: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 20
  },
  resultButtons: { gap: 10 },
  timeoutShade: { flex: 1, backgroundColor: '#000000A0' },
  timeoutScroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  timeoutPanel: {
    width: '100%',
    maxWidth: 440,
    padding: 24,
    gap: 22,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D4AF37',
    backgroundColor: colors.bg
  },
  timeoutTitle: { color: colors.cream, fontSize: 25, fontWeight: '800', textAlign: 'center' },
  timeoutCountdown: {
    color: '#FFE0AD',
    fontSize: 56,
    fontWeight: '900',
    textAlign: 'center',
    fontVariant: ['tabular-nums']
  },
  timeoutDescription: { color: colors.cream, fontSize: 15, lineHeight: 23, textAlign: 'center' },
  timeoutHelp: { color: colors.muted, fontSize: 13, lineHeight: 21, textAlign: 'center' },
  eye: {
    width: 22,
    height: 14,
    borderWidth: 1.5,
    borderColor: colors.cream,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center'
  },
  eyePupil: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.cream },
  eyeSlash: {
    position: 'absolute',
    width: 27,
    height: 2,
    backgroundColor: colors.cream,
    transform: [{ rotate: '-45deg' }]
  },
  root: { flex: 1, backgroundColor: colors.bg },
  flex: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 14
  },
  brand: { fontSize: 23, color: colors.cream, fontWeight: '900', letterSpacing: 3 },
  brandSuit: { color: colors.accent },
  caption: { fontSize: 12, lineHeight: 18, color: colors.muted },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 22 },
  eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 2, color: colors.accent },
  title: { fontSize: 27, fontWeight: '800', letterSpacing: -0.7, color: colors.cream },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: colors.cream },
  page: { paddingHorizontal: 22, paddingTop: 12, paddingBottom: 26, gap: 18 },
  profileCircle: {
    width: 46,
    height: 46,
    borderRadius: 17,
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  avatarText: { color: colors.accent, fontSize: 19, fontWeight: '700' },
  hero: { minHeight: 292, paddingTop: 10, paddingBottom: 32, overflow: 'hidden' },
  pill: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 20
  },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.green },
  pillText: { color: colors.green, fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  heroTitle: {
    fontSize: 43,
    lineHeight: 48,
    fontWeight: '900',
    letterSpacing: -1.6,
    color: colors.cream,
    marginTop: 22
  },
  heroDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.muted,
    marginTop: 16,
    maxWidth: '57%'
  },
  heroCards: { position: 'absolute', right: 9, bottom: 8, width: 143, height: 153 },
  heroCardLeft: { position: 'absolute', left: 0, top: 15, transform: [{ rotate: '-19deg' }] },
  heroCardRight: { position: 'absolute', left: 56, top: 0, transform: [{ rotate: '13deg' }] },
  playTile: {
    backgroundColor: colors.accent,
    borderRadius: 24,
    padding: 18,
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13
  },
  tileIcon: {
    width: 46,
    height: 52,
    borderRadius: 13,
    backgroundColor: '#D4AF37',
    alignItems: 'center',
    justifyContent: 'center'
  },
  tileSuit: { fontSize: 32, color: colors.bg },
  playTitle: { fontSize: 20, fontWeight: '800', color: colors.bg, letterSpacing: -0.5 },
  playDescription: { color: '#4E4016', fontSize: 12, marginTop: 5 },
  playArrow: { fontSize: 30, color: colors.bg },
  networkTile: {
    backgroundColor: colors.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12
  },
  infoRow: { flexDirection: 'row', justifyContent: 'space-evenly', paddingVertical: 12 },
  infoItem: { alignItems: 'center', gap: 5 },
  infoNumber: { color: colors.cream, fontSize: 22, fontWeight: '700' },
  infoDivider: { width: 1, backgroundColor: colors.line },
  rulesLink: { alignItems: 'center', gap: 6, paddingVertical: 8 },
  link: { color: colors.accent, fontSize: 13, fontWeight: '700' },
  tabBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 9,
    gap: 8
  },
  tab: { flex: 1, borderRadius: 16, alignItems: 'center', paddingVertical: 8, gap: 3 },
  tabSelected: { backgroundColor: colors.panel },
  tabIcon: { color: colors.muted, fontSize: 21 },
  tabText: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  tabTextSelected: { color: colors.accent },
  button: {
    borderRadius: 15,
    backgroundColor: colors.accent,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12
  },
  buttonText: { color: colors.bg, fontWeight: '800', fontSize: 14 },
  secondaryButton: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line },
  secondaryButtonText: { color: colors.cream },
  smallButton: { minHeight: 44, paddingHorizontal: 12 },
  compactButton: { minHeight: 36, paddingHorizontal: 9, paddingVertical: 8 },
  compactButtonText: { fontSize: 12 },
  disabled: { opacity: 0.35 },
  pressed: { opacity: 0.75 },
  panel: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    borderRadius: 22,
    gap: 14
  },
  field: { gap: 8 },
  label: { color: colors.cream, fontSize: 13, fontWeight: '600' },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bg
  },
  input: {
    flex: 1,
    minWidth: 0,
    color: colors.cream,
    fontSize: 15,
    paddingHorizontal: 13,
    paddingVertical: 12,
    minHeight: 48
  },
  reveal: { padding: 10 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10
  },
  roomCode: { fontSize: 21, color: colors.cream, letterSpacing: 3, fontWeight: '800' },
  emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 22, padding: 20 },
  refresh: { padding: 12 },
  profileHero: { alignItems: 'center', gap: 10, paddingVertical: 12 },
  largeAvatar: {
    width: 82,
    height: 82,
    borderRadius: 29,
    backgroundColor: '#24382B',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.accent
  },
  largeInitial: { fontSize: 38, color: colors.accent, fontWeight: '700' },
  footer: {
    fontSize: 10,
    color: colors.muted,
    lineHeight: 19,
    textAlign: 'center',
    letterSpacing: 0.6,
    paddingVertical: 15
  },
  modalShade: { flex: 1, backgroundColor: '#000000A0', justifyContent: 'flex-end' },
  modalSafe: { maxHeight: '94%' },
  sheet: {
    backgroundColor: colors.bg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 22,
    paddingBottom: 12,
    maxHeight: '100%'
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.line,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 12
  },
  sheetBody: { gap: 20, paddingVertical: 18 },
  chips: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  chip: {
    flex: 1,
    minWidth: 54,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel
  },
  chipSelected: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  chipTextSelected: { color: colors.bg },
  ruleNumber: { color: colors.accent, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 },
  modalNotice: { padding: 15, color: colors.cream, backgroundColor: '#58342B' },
  toast: {
    position: 'absolute',
    bottom: 90,
    left: 20,
    right: 20,
    backgroundColor: '#274132',
    padding: 16,
    borderRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#6F7953'
  },
  toastText: { color: colors.cream, lineHeight: 20, fontSize: 13 },
  gameHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10
  },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  patreonButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF29',
    borderRadius: 13,
    backgroundColor: '#0B0B0B'
  },
  navIcon: { fontSize: 28, color: colors.cream },
  roundBadge: {
    color: colors.muted,
    fontSize: 11,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14
  },
  gameBody: { flex: 1, minHeight: 0, paddingHorizontal: 12, paddingBottom: 6, gap: 8 },
  playArea: { flex: 1, minHeight: 0, gap: 8 },
  handArea: { gap: 6, minHeight: 0 },
  players: { flexDirection: 'row', justifyContent: 'center', gap: 8 },
  player: {
    flex: 1,
    maxWidth: 155,
    alignItems: 'center',
    padding: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 3
  },
  playerDefender: { borderColor: colors.green },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: colors.panel,
    alignItems: 'center',
    justifyContent: 'center'
  },
  playerName: { color: colors.cream, fontWeight: '600', fontSize: 13 },
  miniBacks: { flexDirection: 'row', paddingVertical: 0 },
  miniBack: {
    width: 13,
    height: 19,
    backgroundColor: '#184C35',
    borderWidth: 1,
    borderColor: '#D4AF37',
    borderRadius: 3,
    marginLeft: -2
  },
  table: {
    backgroundColor: '#145F44',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#D4AF37',
    padding: 10,
    flex: 1,
    minHeight: 0
  },
  tableTop: { flexDirection: 'row', justifyContent: 'space-between' },
  tableLabel: { color: '#B2D2BC', fontSize: 9, fontWeight: '700', letterSpacing: 1.2 },
  trumpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4
  },
  trump: { color: colors.cream, fontWeight: '700', fontSize: 14 },
  trumpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F6EFDF',
    borderColor: colors.accent,
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3
  },
  trumpSymbol: { fontSize: 32, lineHeight: 37, fontWeight: '700' },
  trumpLabel: { color: '#526044', fontSize: 8, fontWeight: '800', letterSpacing: 1 },
  trumpName: { color: '#12261A', fontSize: 14, fontWeight: '800' },
  actionBar: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 8,
    minHeight: 58,
    justifyContent: 'center'
  },
  actionRow: { flexDirection: 'row', gap: 6, alignItems: 'stretch' },
  actionButton: { flex: 1, minWidth: 0, minHeight: 44, paddingHorizontal: 4 },
  emptyTable: { flex: 1, minHeight: 0, alignItems: 'center', justifyContent: 'center' },
  arena: { flex: 1, minHeight: 0, position: 'relative', marginVertical: 4 },
  tableWatermark: { color: '#216D4F', fontSize: 65 },
  pairs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
    paddingVertical: 18
  },
  pair: { width: 82, height: 108 },
  defendCard: { position: 'absolute', top: 18, left: 17, transform: [{ rotate: '10deg' }] },
  tableBottom: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  status: { flex: 1, color: colors.cream, fontSize: 13, fontWeight: '600', lineHeight: 19 },
  timer: { color: colors.accent, fontSize: 18, fontWeight: '800' },
  card: {
    width: 78,
    height: 112,
    borderRadius: 10,
    backgroundColor: '#F6EFDF',
    borderWidth: 2,
    borderColor: '#D5CDBF',
    padding: 7,
    overflow: 'hidden'
  },
  cardSmall: { width: 60, height: 86, padding: 5, borderRadius: 8 },
  cardActive: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: '#FFF9EC',
    transform: [{ translateY: -5 }]
  },
  cardDim: { borderColor: '#B8B0A0' },
  cardRank: { color: '#12261A', fontSize: 22, fontWeight: '800', lineHeight: 26 },
  cardRankSmall: { fontSize: 17, lineHeight: 20 },
  cardSuit: { color: '#12261A', fontSize: 38, textAlign: 'center', lineHeight: 43 },
  cardSuitSmall: { fontSize: 29, lineHeight: 32 },
  cardCorner: { position: 'absolute', bottom: 4, right: 6, fontSize: 14, color: '#12261A' },
  red: { color: colors.red },
  handLabel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6
  },
  hand: { gap: 8, alignItems: 'center' },
  handHint: { color: colors.muted, fontSize: 11, textAlign: 'center' },
  actions: { flexDirection: 'row', gap: 8, justifyContent: 'center', flexWrap: 'wrap' },
  result: { backgroundColor: colors.panel, padding: 20, borderRadius: 22, gap: 12 },
  warning: { color: colors.accent, padding: 12, textAlign: 'center', fontSize: 13 }
});
